name: my_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^9.3.0+1
  flutter_svg: ^2.1.0
  stylish_bottom_bar: ^1.1.1
  socket_io_client: ^3.1.2
  flutter_riverpod: ^2.6.1
  dio: ^5.9.0
  flutter_secure_storage: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/users/
    - assets/icons/
    - assets/fonts/
    - assets/logos/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
